# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test0515.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 399)
        Dialog.setStyleSheet("background-color: rgb(85, 83, 87);")
        self.pressMeButton = QtWidgets.QPushButton(Dialog)
        self.pressMeButton.setGeometry(QtCore.QRect(128, 240, 154, 29))
        self.pressMeButton.setStyleSheet("background-color: rgb(130, 135, 139);\n"
"font: 11pt \"Adobe Arabic\";\n"
"color: rgb(255, 255, 255);")
        self.pressMeButton.setObjectName("pressMeButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(128, 100, 154, 51))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.helloButton = QtWidgets.QPushButton(Dialog)
        self.helloButton.setGeometry(QtCore.QRect(128, 200, 154, 29))
        self.helloButton.setStyleSheet("background-color: rgb(130, 135, 139);\n"
"font: 11pt \"Adobe Arabic\";\n"
"color: rgb(255, 255, 255);")
        self.helloButton.setObjectName("helloButton")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(130, 170, 151, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 91, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("moon.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pressMeButton.setText(_translate("Dialog", "Press me"))
        self.label.setText(_translate("Dialog", "Please enter value"))
        self.helloButton.setText(_translate("Dialog", "Show string"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
